name: smart_home_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.0
  speech_to_text: 6.6.0
  firebase_core: ^2.27.1
  firebase_database: ^10.4.10
  fl_chart: ^0.66.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
