Map<String, String> commandsDictionary = {
  'disable': 'disable',
  'enable': 'enable',
  'value': 'value',
  'вимкнути': 'disable',
  'отключить': 'disable',
  'значення': 'value',
  'значение': 'value',
  'включи': 'enable',
  'увімкни': 'enable',
  'выключить': 'disable',
  'выключи': 'disable',
  'отключи': 'disable',
  'вкл': 'enable',
  'включить': 'enable',
  'включение': 'enable',
  'отключение': 'disable',
  'значение параметра': 'value',
  'параметр': 'value',
  'активировать': 'enable',
  'деактивировать': 'disable',
  'включиться': 'enable',
  'отключиться': 'disable',
  'восстановить': 'enable',
  'выставить': 'value',
};
