// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8_bAsOum1_MKvqCejo4XY62hehjhsR3M',
    appId: '1:870283002233:web:774e45b4f6d8701b61afa8',
    messagingSenderId: '870283002233',
    projectId: 'smarthomeapplication-6c380',
    authDomain: 'smarthomeapplication-6c380.firebaseapp.com',
    databaseURL: 'https://smarthomeapplication-6c380-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarthomeapplication-6c380.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABcixC2LWBR--DOTVA8QFNYtekXf13FF8',
    appId: '1:870283002233:android:5bdefd082f0dc64661afa8',
    messagingSenderId: '870283002233',
    projectId: 'smarthomeapplication-6c380',
    databaseURL: 'https://smarthomeapplication-6c380-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarthomeapplication-6c380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1EA1xAGDHfV1BoPV1bWSq475f73yto6M',
    appId: '1:870283002233:ios:25184ac8d71b5e0e61afa8',
    messagingSenderId: '870283002233',
    projectId: 'smarthomeapplication-6c380',
    databaseURL: 'https://smarthomeapplication-6c380-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarthomeapplication-6c380.appspot.com',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1EA1xAGDHfV1BoPV1bWSq475f73yto6M',
    appId: '1:870283002233:ios:779b1768102379f961afa8',
    messagingSenderId: '870283002233',
    projectId: 'smarthomeapplication-6c380',
    databaseURL: 'https://smarthomeapplication-6c380-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarthomeapplication-6c380.appspot.com',
    iosBundleId: 'com.example.smartHomeApp.RunnerTests',
  );
}
